## traefik - EntryPoints
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  ## link tot mkcerts
  file:
    directory: /etc/traefik/certificates
    watch: true ## check voor updates
  
  ## traefik - Traefik & Docker
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true ## check voor updates

api:
  dashboard: true
