tls:
  certificates:
    - certFile: /certs/moodle.local.pem
      keyFile: /certs/moodle.local-key.pem
    - certFile: /certs/traefik.local.pem
      keyFile: /certs/traefik.local-key.pem
    - certFile: /certs/ltitool.local.pem
      keyFile: /certs/ltitool.local-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/traefik.local.pem
        keyFile: /certs/traefik.local-key.pem